### PR TITLE
added getting-started tutorial

### PR DESCRIPTION
**Pull request by emmanuelJet**
This pull request consists of the Getting Started Tutorials which a live preview can be seen at [https://emmanueljet.github.io/documentation-hub/site](https://emmanueljet.github.io/documentation-hub/site). Below are changes made:
 	
 new file:   docs/getting-started/advance-to-do-aepp/README.md
	new file:   docs/getting-started/coding-locally-with-aeproject/README.md
	new file:   docs/getting-started/deploying-on-mainnet/README.md
	new file:   docs/getting-started/deploying-on-testnet/README.md
	new file:   docs/getting-started/hello-world-with-sophia/README.md
	modified:   docs/quick_glossary.md
	modified:   mkdocs.yml
	modified:   site/404.html
	new file:   site/getting-started/advance-to-do-aepp/index.html
	new file:   site/getting-started/coding-locally-with-aeproject/index.html
	new file:   site/getting-started/deploying-on-mainnet/index.html
	new file:   site/getting-started/deploying-on-testnet/index.html
	new file:   site/getting-started/hello-world-with-sophia/index.html
	modified:   site/index.html
	modified:   site/quick_glossary/index.html

### CODE REVIEW

**Comment by emmanuelJet** [comment]
I am adding links to video tutorials and also correcting a few words. This will be published at the next commit.

**Comment by emmanuelJet** [comment]
Good to go

**Comment by omar-saadoun** [comment]
@thepiwo can we merge jet PR?

**Review by omar-saadoun — APPROVED** [review]

**Comment by thepiwo** [comment]
@omar-saadoun I don't have the permission in this repository

**Comment by omar-saadoun** [comment]
@dincho can you do it?

**Review by venimus — APPROVED** [review]
formal approve

**Review by omar-saadoun — APPROVED** [review]

**Review by omar-saadoun — APPROVED** [review]

**Pull request merged**
